create extension if not exists "pgcrypto";
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text unique not null, full_name text, avatar_url text, created_at timestamptz not null default now());
create table if not exists public.plans (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, title text not null, location text not null, starts_at timestamptz, caption text, image_url text, created_at timestamptz not null default now());
create table if not exists public.plan_members (plan_id uuid references public.plans(id) on delete cascade, user_id uuid references public.profiles(id) on delete cascade, created_at timestamptz not null default now(), primary key (plan_id, user_id));
alter table public.profiles enable row level security;
alter table public.plans enable row level security;
alter table public.plan_members enable row level security;
create policy "Profiles are public" on public.profiles for select using (true);
create policy "Users create their profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users update their profile" on public.profiles for update using (auth.uid() = id);
create policy "Plans are public" on public.plans for select using (true);
create policy "Signed in users create plans" on public.plans for insert with check (auth.uid() = user_id);
create policy "Owners update plans" on public.plans for update using (auth.uid() = user_id);
create policy "Members are public" on public.plan_members for select using (true);
create policy "Users join plans" on public.plan_members for insert with check (auth.uid() = user_id);
create policy "Users leave plans" on public.plan_members for delete using (auth.uid() = user_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, username, full_name) values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)), new.raw_user_meta_data->>'full_name'); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
