const posts = [
  {user:'maya.rose', name:'Maya Rose', avatar:'https://i.pravatar.cc/100?img=25', time:'2h', image:'pic-one', title:'Sunset picnic', location:'Prospect Park · Today, 5:00 PM', caption:'The blanket is packed and the sky is looking promising. Bringing snacks, sketchbooks, and room for a few more. Who’s in? ✦', likes:128, comments:14, joined:false},
  {user:'ari.makes', name:'Ari M.', avatar:'https://i.pravatar.cc/100?img=47', time:'5h', image:'pic-two', title:'Sunday people', location:'Red Hook · Sun, 10:30 AM', caption:'A little walk, a really good coffee, and some new neighborhood friends. Low-pressure plans are the best plans.', likes:86, comments:9, joined:false}
];
const postsEl=document.querySelector('#posts');
const mapUrl=place=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place)}`;
function renderPosts(){postsEl.innerHTML=posts.map((post,index)=>`<article class="post"><header class="post-head"><img src="${post.avatar}" alt="${post.name}"><div><strong>${post.user}</strong><small>${post.time} · <a class="place" href="${mapUrl(post.location)}" target="_blank" rel="noreferrer">${post.location} ↗</a></small></div><button class="more">•••</button></header><div class="post-visual ${post.image}"><div class="visual-label"><small>upneXt plan</small><h2>${post.title}</h2><p>${post.location}</p></div></div><div class="post-actions"><button class="action like ${post.liked?'liked':''}" data-index="${index}">${post.liked?'♥':'♡'}</button><button class="action comment" data-index="${index}">◯</button><button class="action share" data-index="${index}">⌁</button><button class="action save ${post.saved?'saved':''}" data-index="${index}">${post.saved?'◆':'◇'}</button></div><div class="post-body"><p class="likes">${post.likes+(post.liked?1:0)} likes</p><p class="caption"><strong>${post.user}</strong>${post.caption} <a href="#">#${post.title.replaceAll(' ','')}</a></p><p class="comments">View all ${post.comments} comments</p></div></article>`).join('');
  document.querySelectorAll('.like').forEach(btn=>btn.onclick=()=>{const p=posts[btn.dataset.index];p.liked=!p.liked;renderPosts()});document.querySelectorAll('.save').forEach(btn=>btn.onclick=()=>{posts[btn.dataset.index].saved=!posts[btn.dataset.index].saved;showToast(posts[btn.dataset.index].saved?'Saved to your plans':'Removed from saved plans');renderPosts()});document.querySelectorAll('.share').forEach(btn=>btn.onclick=()=>showToast('Plan link copied to clipboard ✦'));document.querySelectorAll('.comment').forEach(btn=>btn.onclick=()=>showToast('Comments are coming next ✦'));
}
renderPosts();
const modal=document.querySelector('#modal');document.querySelector('#open-modal').onclick=()=>modal.classList.add('open');document.querySelector('#close-modal').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
document.querySelector('#post-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);posts.unshift({user:'jamie.morgan',name:'Jamie Morgan',avatar:'https://i.pravatar.cc/100?img=68',time:'now',image:'pic-one',title:data.get('title'),location:data.get('where')+' · '+data.get('when'),caption:data.get('caption')||'A new plan is taking shape. Come as you are and make it yours. ✦',likes:0,comments:0,liked:false,saved:false});renderPosts();modal.classList.remove('open');e.target.reset();showToast('Your plan is live on upneXt ✦')};
function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
