(function(){
let posts = [
  {user:'maya.rose', name:'Maya Rose', avatar:'https://i.pravatar.cc/100?img=25', time:'2h', image:'pic-one', category:'Outdoors', title:'Sunset picnic', location:'Prospect Park · Today, 5:00 PM', caption:'The blanket is packed and the sky is looking promising. Bringing snacks, sketchbooks, and room for a few more. Who’s in? ✦', likes:128, comments:14, joined:false},
  {user:'ari.makes', name:'Ari M.', avatar:'https://i.pravatar.cc/100?img=47', time:'5h', image:'pic-two', category:'Social', title:'Sunday people', location:'Red Hook · Sun, 10:30 AM', caption:'A little walk, a really good coffee, and some new neighborhood friends. Low-pressure plans are the best plans.', likes:86, comments:9, joined:false}
];
const postsEl=document.querySelector('#posts');
const hasSupabase=window.SUPABASE_URL&&!window.SUPABASE_URL.startsWith('YOUR_')&&window.SUPABASE_ANON_KEY&&!window.SUPABASE_ANON_KEY.startsWith('YOUR_');
const supabase=hasSupabase&&window.supabase?.createClient?window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY):null;
let currentUser=null;
let savedEventIds=new Set(JSON.parse(localStorage.getItem('evenit-saved-events')||'[]'));
let joinedEventIds=new Set(JSON.parse(localStorage.getItem('evenit-joined-events')||'[]'));
let adminContent={};
 function updateAccountUI(){const loginButton=document.querySelector('#open-login');const navAvatar=document.querySelector('#nav-avatar');if(currentUser){const name=currentUser.user_metadata?.full_name||currentUser.email?.split('@')[0]||'Evenit member';const avatar=currentUser.user_metadata?.avatar_url;loginButton.hidden=true;navAvatar.textContent=name.slice(0,2).toUpperCase();if(avatar)navAvatar.innerHTML=`<img src="${avatar}" alt="">`}else{loginButton.hidden=false;navAvatar.textContent='EV'}}
const mapUrl=place=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place)}`;
async function loadPlans(){if(!supabase)return;const {data,error}=await supabase.from('plans').select('id,title,location,starts_at,caption,category,user_id').order('created_at',{ascending:false});if(error){showToast('Could not load plans: '+error.message);return}if(data?.length){posts=data.map(plan=>({id:plan.id,user:'Evenit member',name:'Evenit member',avatar:'https://i.pravatar.cc/100?img=68',time:'new',image:'pic-one',category:plan.category||'Community event',title:plan.title,location:plan.location,caption:plan.caption||'A new event is taking shape. Come as you are and make it yours. ✦',likes:0,comments:0,joined:joinedEventIds.has(plan.id),saved:savedEventIds.has(plan.id)}))}renderPosts();applyAdminContent();applyAdminStyles()}
async function toggleJoin(index){const post=posts[index];if(!supabase||!currentUser){showToast('Create a profile before joining this event');signupModal.classList.add('open');return}if(post.id){if(post.joined){const {error}=await supabase.from('plan_members').delete().eq('plan_id',post.id).eq('user_id',currentUser.id);if(error){showToast(error.message);return}}else{const {error}=await supabase.from('plan_members').insert({plan_id:post.id,user_id:currentUser.id});if(error){showToast(error.message);return}}}post.joined=!post.joined;if(post.id){post.joined?joinedEventIds.add(post.id):joinedEventIds.delete(post.id);localStorage.setItem('evenit-joined-events',JSON.stringify([...joinedEventIds]))}showToast(post.joined?'You’ve joined this event ✦':'You left this event');renderPosts()}
function renderPosts(){postsEl.innerHTML=posts.map((post,index)=>`<article class="post"><header class="post-head"><img src="${post.avatar}" alt="${post.name}"><div><strong>${post.user}</strong><small>${post.time} · <a class="place" href="${mapUrl(post.location)}" target="_blank" rel="noreferrer">${post.location} ↗</a></small></div><button class="more">•••</button></header><div class="post-visual ${post.image}"><div class="visual-label"><small class="visual-category">${post.category||'COMMUNITY EVENT'}</small><h2>${post.title}</h2><p>${post.location}</p></div></div><div class="post-actions"><button class="action like ${post.liked?'liked':''}" data-index="${index}">${post.liked?'👍':'👍🏻'}</button><button class="action comment" data-index="${index}">◯</button><button class="action share" data-index="${index}">⌁</button><button class="action save ${post.saved?'saved':''}" data-index="${index}">${post.saved?'◆':'◇'}</button></div><div class="post-body"><p class="likes">${post.likes+(post.liked?1:0)} people are interested</p><p class="caption"><strong>${post.user}</strong>${post.caption} <a href="#">#${post.title.replaceAll(' ','')}</a></p><p class="comments">View all ${post.comments} comments</p><button class="join-plan ${post.joined?'joined':''}" data-index="${index}">${post.joined?'Joined ✓':'Join in'} <span>→</span></button></div></article>`).join('');
  document.querySelectorAll('.like').forEach(btn=>btn.onclick=()=>{const p=posts[btn.dataset.index];p.liked=!p.liked;renderPosts()});document.querySelectorAll('.save').forEach(btn=>btn.onclick=()=>{const post=posts[btn.dataset.index];post.saved=!post.saved;post.saved?savedEventIds.add(post.id||post.title):savedEventIds.delete(post.id||post.title);localStorage.setItem('evenit-saved-events',JSON.stringify([...savedEventIds]));showToast(post.saved?'Saved to your events':'Removed from saved events');renderPosts()});document.querySelectorAll('.share').forEach(btn=>btn.onclick=()=>showToast('Event link copied to clipboard ✦'));document.querySelectorAll('.comment').forEach(btn=>btn.onclick=()=>showToast('Comments are coming next ✦'));document.querySelectorAll('.join-plan').forEach(btn=>btn.onclick=()=>toggleJoin(btn.dataset.index));document.querySelectorAll('.more').forEach(btn=>btn.onclick=()=>showToast('More event actions are coming next ✦'));
}
renderPosts();
const pageView=document.querySelector('#page-view');
const homeElements=[document.querySelector('.feed-top'),document.querySelector('.stories'),postsEl];
const pageTemplates={
  discover:`<div class="page-header"><p class="overline">Find your people</p><h2>Discover plans<br><em>worth joining.</em></h2><div class="search-box">⌕ <input placeholder="Search plans, places, or people..."></div></div><div class="discover-grid"><div class="discover-tile tile-violet"><small>OUTDOORS</small><strong>Golden hour<br>on the water</strong><span>16 people going →</span></div><div class="discover-tile tile-gold"><small>FOOD & DRINK</small><strong>Sunday supper<br>club</strong><span>12 people going →</span></div><div class="discover-tile tile-ink"><small>CREATIVE</small><strong>Make a tiny<br>zine together</strong><span>8 people going →</span></div></div>`,
  notifications:`<div class="page-header"><p class="overline">Stay in the loop</p><h2>Notifications</h2></div><div class="activity-list"><div class="activity"><img src="https://i.pravatar.cc/100?img=47"><p><strong>ari.makes</strong> joined your plan <b>Sunset picnic</b><small>12 minutes ago</small></p></div><div class="activity"><img src="https://i.pravatar.cc/100?img=25"><p><strong>maya.rose</strong> liked your plan <b>Saturday sketch walk</b><small>1 hour ago</small></p></div><div class="activity"><img src="https://i.pravatar.cc/100?img=44"><p><strong>theo.walks</strong> started following you<small>Yesterday</small></p></div></div>`,
  messages:`<div class="page-header"><p class="overline">Keep the plan moving</p><h2>Messages</h2></div><div class="message-list"><div class="message"><img src="https://i.pravatar.cc/100?img=25"><div><strong>maya.rose</strong><p>Should we bring extra blankets for the picnic?</p></div><small>2m</small></div><div class="message"><img src="https://i.pravatar.cc/100?img=47"><div><strong>ari.makes</strong><p>That coffee walk sounds perfect.</p></div><small>1h</small></div><div class="empty-message">Your conversations will live here.<br><span>Join a plan to meet someone new.</span></div></div>`,
  settings:`<div class="page-header"><p class="overline">Make it yours</p><h2>Settings</h2></div><div class="settings-list"><button>Account details <span>→</span></button><button>Notification preferences <span>→</span></button><button>Privacy and safety <span>→</span></button><button>Help center <span>→</span></button></div>`,
};
function renderProfile(){const loggedIn=Boolean(currentUser);const name=currentUser?.user_metadata?.full_name||currentUser?.email?.split('@')[0]||'Your profile';const username=currentUser?.user_metadata?.username||'create your username';pageView.innerHTML=`<div class="profile-cover"></div><div class="profile-intro"><img src="${currentUser?.user_metadata?.avatar_url||'https://i.pravatar.cc/160?img=68'}"><div><p class="overline">Your profile</p><h2>${name}</h2><p class="profile-handle">${loggedIn?'@'+username:'Start your upneXt story'}</p></div>${loggedIn?'<button class="edit-profile">Edit profile</button>':''}</div><div class="profile-stats"><span><strong>0</strong> plans posted</span><span><strong>0</strong> joined</span><span><strong>0</strong> followers</span></div><div class="profile-tabs"><button class="active">Your plans</button><button>Joined</button><button>Saved</button></div><div class="profile-empty"><span>✦</span><h3>${loggedIn?'Your plans will appear here':'Join the community'}</h3><p>${loggedIn?'Share an idea and give people a reason to show up.':'Create your profile to post events and join other people’s plans.'}</p>${loggedIn?'<button class="publish-button" id="profile-post">Create an event <span>→</span></button>':'<div class="profile-actions"><button class="publish-button" id="profile-signup">Create a profile</button><button class="profile-login-button" id="profile-login">Log in</button></div>'}</div>`;if(loggedIn)document.querySelector('#profile-post').onclick=()=>modal.classList.add('open');else{document.querySelector('#profile-signup').onclick=()=>signupModal.classList.add('open');document.querySelector('#profile-login').onclick=()=>loginModal.classList.add('open')}}
function renderDiscover(){pageView.innerHTML=pageTemplates.discover+`<div class="discover-results"><div class="section-label">Live plans from the community</div>${posts.map((post,index)=>`<article class="discover-result"><div><strong>${post.title}</strong><small>${post.location}</small><p>${post.caption}</p></div><button class="join-plan ${post.joined?'joined':''}" data-index="${index}">${post.joined?'Joined ✓':'Join in'} <span>→</span></button></article>`).join('')}</div>`;document.querySelectorAll('.join-plan').forEach(btn=>btn.onclick=()=>toggleJoin(btn.dataset.index))}
async function renderNotifications(){if(!supabase||!currentUser){pageView.innerHTML=pageTemplates.notifications;return}const {data}=await supabase.from('notifications').select('message,created_at').order('created_at',{ascending:false}).limit(20);pageView.innerHTML=`<div class="page-header"><p class="overline">Stay in the loop</p><h2>Notifications</h2></div><div class="activity-list">${data?.length?data.map(item=>`<div class="activity"><span class="notification-mark">✦</span><p>${item.message}<small>${new Date(item.created_at).toLocaleString()}</small></p></div>`).join(''):'<div class="empty-message">No notifications yet.<br><span>Join a plan or follow a topic to get updates.</span></div>'}</div>`}
function setPage(page){homeElements.forEach(element=>element.hidden=page!=='home');pageView.hidden=page==='home';document.querySelectorAll('[data-page]').forEach(link=>link.classList.toggle('active',link.dataset.page===page));if(page!=='home'){if(page==='profile')renderProfile();else if(page==='discover')renderDiscover();else if(page==='notifications')renderNotifications();else pageView.innerHTML=pageTemplates[page]||pageTemplates.settings}window.scrollTo({top:0,behavior:'smooth'})}
function renderProfileTab(tab){const content=document.querySelector('.profile-empty');if(!content)return;const key=tab.textContent.toLowerCase();const items=key.includes('joined')?posts.filter(post=>post.joined):key.includes('saved')?posts.filter(post=>savedEventIds.has(post.id||post.title)):posts.filter(post=>post.user==='Evenit member'||post.user==='jamie.morgan');content.innerHTML=items.length?items.map(post=>`<div class="profile-event"><span>✦</span><div><strong>${post.title}</strong><small>${post.location}</small></div></div>`).join(''):`<span>✦</span><h3>No ${key} events yet</h3><p>Your ${key} events will appear here.</p>${key==='your plans'?'<button class="publish-button" id="profile-post">Create an event <span>→</span></button>':''}`;const create=document.querySelector('#profile-post');if(create)create.onclick=()=>modal.classList.add('open')}
document.querySelectorAll('[data-page]').forEach(link=>link.onclick=e=>{e.preventDefault();setPage(link.dataset.page)});
if(supabase){supabase.auth.getSession().then(({data})=>{currentUser=data.session?.user||null;updateAccountUI();loadPlans()});supabase.auth.onAuthStateChange((_event,session)=>{currentUser=session?.user||null;updateAccountUI();if(session?.user&&pageView&&!pageView.hidden)renderProfile()})}else{updateAccountUI();loadPlans()}
const modal=document.querySelector('#modal');document.querySelector('#open-modal').onclick=()=>modal.classList.add('open');document.querySelector('#close-modal').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
const loginModal=document.querySelector('#login-modal');const openLogin=()=>loginModal.classList.add('open');document.querySelector('#open-login').onclick=openLogin;document.querySelector('#open-login-mobile').onclick=openLogin;document.querySelector('#close-login').onclick=()=>loginModal.classList.remove('open');loginModal.onclick=e=>{if(e.target===loginModal)loginModal.classList.remove('open')};document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();const data=new FormData(e.target);if(!supabase){showToast('Supabase is not available. Check the connection settings.');return}const {data:result,error}=await supabase.auth.signInWithPassword({email:data.get('email'),password:data.get('password')});if(error){showToast(error.message);return}currentUser=result.user;updateAccountUI();loginModal.classList.remove('open');showToast('Welcome back to upneXt ✦')};document.querySelector('#signup-link').onclick=e=>{e.preventDefault();loginModal.classList.remove('open');signupModal.classList.add('open')};
const signupModal=document.querySelector('#signup-modal');document.querySelector('#close-signup').onclick=()=>signupModal.classList.remove('open');signupModal.onclick=e=>{if(e.target===signupModal)signupModal.classList.remove('open')};document.querySelector('#signup-link').onclick=e=>{e.preventDefault();loginModal.classList.remove('open');signupModal.classList.add('open')};document.querySelector('#back-to-login').onclick=e=>{e.preventDefault();signupModal.classList.remove('open');loginModal.classList.add('open')};document.querySelector('#signup-form').onsubmit=async e=>{e.preventDefault();const data=new FormData(e.target);if(!supabase){showToast('Supabase is not available. Check the connection settings.');return}const {data:result,error}=await supabase.auth.signUp({email:data.get('email'),password:data.get('password'),options:{emailRedirectTo:window.location.href,data:{username:data.get('username'),full_name:data.get('full_name'),neighborhood:data.get('neighborhood'),interest:data.get('interest')}}});if(error){showToast(error.message);return}currentUser=result.session?result.user:null;updateAccountUI();signupModal.classList.remove('open');showToast(result.session?'Profile created and you are signed in ✦':'Check your email to verify your profile, then log in ✦');setPage('profile')};
document.querySelector('#post-form').onsubmit=async e=>{e.preventDefault();const data=new FormData(e.target);if(!supabase||!currentUser){showToast('Log in before posting a plan');loginModal.classList.add('open');return}const {error}=await supabase.from('plans').insert({user_id:currentUser.id,title:data.get('title'),location:data.get('where'),caption:data.get('caption'),category:data.get('category')}).select().single();if(error){showToast(error.message);return}modal.classList.remove('open');e.target.reset();await loadPlans();showToast('Your plan is live on upneXt ✦')};
function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
document.querySelectorAll('.story').forEach(story=>story.onclick=()=>showToast(story.classList.contains('add-story')?'Story posting is coming next ✦':'Stories are coming next ✦'));
document.querySelector('.feed-filter').onclick=()=>{const filter=document.querySelector('.feed-filter');filter.dataset.mode=filter.dataset.mode==='following'?'for-you':'following';filter.innerHTML=filter.dataset.mode==='following'?'Following <span>⌄</span>':'For you <span>⌄</span>';showToast(filter.dataset.mode==='following'?'Showing plans from people you follow':'Showing plans picked for you')};
document.querySelectorAll('.suggestion button').forEach(button=>button.onclick=()=>{button.textContent=button.textContent==='Follow'?'Following':'Follow';showToast(button.textContent==='Following'?'You are now following this profile ✦':'Profile unfollowed')});
document.querySelectorAll('.rail-heading a').forEach(link=>link.onclick=e=>{e.preventDefault();setPage('discover')});
document.querySelectorAll('.trend').forEach(trend=>trend.onclick=()=>showToast('Opening this trending plan ✦'));
document.querySelector('#mobile-menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('mobile-open');
document.querySelector('#forgot-password').onclick=async e=>{e.preventDefault();const email=document.querySelector('#login-form input[name=email]').value;if(!email){showToast('Enter your email address first');return}if(!supabase){showToast('Supabase is not available. Check the connection settings.');return}const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.href});showToast(error?error.message:'Password reset email sent ✦')};
document.addEventListener('click',e=>{const settings=e.target.closest('.settings-list button');if(settings)showToast(`${settings.textContent.replace('→','').trim()} selected`);if(e.target.closest('.edit-profile'))showToast('Profile editing is coming next ✦');const tab=e.target.closest('.profile-tabs button');if(tab){document.querySelectorAll('.profile-tabs button').forEach(item=>item.classList.remove('active'));tab.classList.add('active');const empty=document.querySelector('.profile-empty h3');if(empty)empty.textContent=`${tab.textContent} will appear here`}});
document.addEventListener('click',e=>{const tab=e.target.closest('.profile-tabs button');if(tab)renderProfileTab(tab)});
const editModal=document.querySelector('#edit-modal');const editForm=document.querySelector('#edit-form');document.addEventListener('click',e=>{const identity=e.target.closest('.post-head img,.post-head strong,.suggestion img,.suggestion strong');if(identity){e.preventDefault();setPage('profile')}if(e.target.closest('#edit-profile')){const meta=currentUser?.user_metadata||{};editForm.full_name.value=meta.full_name||'';editForm.username.value=meta.username||'';editForm.email.value=currentUser?.email||'';editModal.classList.add('open')}});document.querySelector('#close-edit').onclick=()=>editModal.classList.remove('open');editModal.onclick=e=>{if(e.target===editModal)editModal.classList.remove('open')};editForm.onsubmit=async e=>{e.preventDefault();if(!supabase||!currentUser){showToast('Log in to edit your profile');return}const data=new FormData(editForm);const metadata={...currentUser.user_metadata,full_name:data.get('full_name'),username:data.get('username')};const {data:result,error:authError}=await supabase.auth.updateUser({data:metadata});if(authError){showToast(authError.message);return}const {error}=await supabase.from('profiles').update({full_name:data.get('full_name'),username:data.get('username'),college:data.get('college')||null,enrollment_id:data.get('enrollment_id')||null,education_public:data.get('college_visibility')==='public'}).eq('id',currentUser.id);if(error){showToast(error.message);return}currentUser=result.user;updateAccountUI();editModal.classList.remove('open');renderProfile();showToast('Profile updated ✦')};
async function uploadProfileMedia(file,type){if(!file)return null;const extension=file.name.split('.').pop().toLowerCase();const path=`${currentUser.id}/${type}-${Date.now()}.${extension}`;const {error}=await supabase.storage.from('profile-media').upload(path,file,{upsert:true,contentType:file.type});if(error)throw error;return supabase.storage.from('profile-media').getPublicUrl(path).data.publicUrl}
editForm.onsubmit=async e=>{e.preventDefault();if(!supabase||!currentUser){showToast('Log in to edit your profile');return}const data=new FormData(editForm);try{const avatarUrl=await uploadProfileMedia(data.get('avatar'),'avatar');const bannerUrl=await uploadProfileMedia(data.get('banner'),'banner');const metadata={...currentUser.user_metadata,full_name:data.get('full_name'),username:data.get('username'),...(avatarUrl?{avatar_url:avatarUrl}:{}),...(bannerUrl?{banner_url:bannerUrl}:{})};const {data:result,error:authError}=await supabase.auth.updateUser({data:metadata});if(authError)throw authError;const {error}=await supabase.from('profiles').update({full_name:data.get('full_name'),username:data.get('username'),college:data.get('college')||null,enrollment_id:data.get('enrollment_id')||null,education_public:data.get('college_visibility')==='public',...(avatarUrl?{avatar_url:avatarUrl}:{}),...(bannerUrl?{banner_url:bannerUrl}:{})}).eq('id',currentUser.id);if(error)throw error;currentUser=result.user;updateAccountUI();editModal.classList.remove('open');renderProfile();showToast('Profile and media updated ✦')}catch(error){showToast(error.message||'Could not update profile media')}};
document.addEventListener('click',e=>{if(e.target.closest('.edit-profile')){const meta=currentUser?.user_metadata||{};editForm.full_name.value=meta.full_name||'';editForm.username.value=meta.username||'';editForm.email.value=currentUser?.email||'';editModal.classList.add('open')}});
async function loadProfileDetails(){if(!supabase||!currentUser)return;const {data}=await supabase.from('profiles').select('college,enrollment_id,education_public,banner_url,avatar_url').eq('id',currentUser.id).maybeSingle();if(!data)return;if(data.banner_url){const cover=document.querySelector('.profile-cover');if(cover)cover.style.backgroundImage=`url("${data.banner_url}")`}if(data.avatar_url){const profileImage=document.querySelector('.profile-intro img');if(profileImage)profileImage.src=data.avatar_url;const navImage=document.querySelector('#nav-avatar img');if(navImage)navImage.src=data.avatar_url}if(editModal.classList.contains('open')){editForm.college.value=data.college||'';editForm.enrollment_id.value=data.enrollment_id||'';editForm.college_visibility.value=data.education_public?'public':'private'}}
document.addEventListener('click',e=>{if(e.target.closest('[data-page="profile"]')||e.target.closest('#edit-profile'))setTimeout(loadProfileDetails,100)});
const photoViewer=document.querySelector('#photo-viewer');document.addEventListener('click',e=>{const photo=e.target.closest('.profile-intro img');if(!photo)return;document.querySelector('#expanded-photo').src=photo.src;photoViewer.classList.add('open')});document.querySelector('#close-photo').onclick=()=>photoViewer.classList.remove('open');photoViewer.onclick=e=>{if(e.target===photoViewer)photoViewer.classList.remove('open')};
document.title='Evenit | Make plans happen';
 async function loadSiteSettings(){if(!supabase)return;const {data}=await supabase.from('site_settings').select('*').single();if(!data)return;document.title=`${data.site_name} | Make plans happen`;document.documentElement.style.setProperty('--violet',data.primary_color);document.documentElement.style.setProperty('--gold',data.accent_color);document.querySelectorAll('.logo').forEach(logo=>logo.textContent=data.site_name);document.querySelectorAll('.like').forEach(button=>button.textContent=data.reaction_icon);const notification=document.querySelector('[data-page="notifications"]');if(notification){const label=[...notification.childNodes].find(node=>node.nodeType===Node.TEXT_NODE&&node.nodeValue.includes('Notifications'));if(label)label.nodeValue=label.nodeValue.replace('Notifications',data.notification_label)}}
loadSiteSettings();
 async function applyAdminContent(){if(!supabase)return;const {data}=await supabase.from('site_settings').select('*').single();const content=data?.content||{};adminContent=content;const setText=(selector,value)=>{if(!value)return;document.querySelectorAll(selector).forEach(element=>{const text=[...element.childNodes].find(node=>node.nodeType===Node.TEXT_NODE&&node.nodeValue.trim());if(text)text.nodeValue=` ${value}`})};const setValue=(selector,value)=>{if(value)document.querySelectorAll(selector).forEach(element=>element.value=value)};setText('.post-button span',content.post_button);setText('.feed-top h1',content.home_title);setText('.feed-filter',content.home_filter);setText('[data-page="discover"]',content.discover_tab);setText('[data-page="notifications"]',content.notification_tab);setText('[data-page="messages"]',content.messages_tab);setText('[data-page="settings"]',content.settings_tab);setText('.stories .add-story small',content.home_story_label);setText('#login-form .publish-button',content.login_button);setText('#signup-form .publish-button',content.signup_button);setText('#edit-form .publish-button',content.save_button);document.querySelectorAll('.join-plan').forEach(button=>{button.childNodes[0].nodeValue=`${button.classList.contains('joined')?'Joined':content.join_button||'Join in'} `});document.querySelectorAll('.like').forEach(button=>button.textContent=data.reaction_icon||content.reaction_icon||'👍🏻');setValue('.search-box input',content.discover_search);if(!pageView.hidden){const title=pageView.querySelector('.page-header h2');const eyebrow=pageView.querySelector('.page-header .overline');if(title&&content.discover_title)title.textContent=content.discover_title;if(eyebrow&&content.discover_eyebrow)eyebrow.textContent=content.discover_eyebrow}document.title=`${data.site_name||'Evenit'} | Make plans happen`}
 applyAdminContent();
 async function applyAdminStyles(){if(!supabase)return;const {data}=await supabase.from('site_settings').select('ui_styles').single();const styles=data?.ui_styles||{};const set=(selector,key,property='color')=>{if(styles[key])document.querySelectorAll(selector).forEach(element=>element.style[property]=styles[key])};set('[data-page="home"]','nav_home');set('[data-page="discover"]','nav_discover');set('[data-page="notifications"]','nav_notifications');set('[data-page="messages"]','nav_messages');set('[data-page="profile"]','nav_profile');set('[data-page="settings"]','nav_settings');set('.post-button,.publish-button','post_button','backgroundColor');set('.join-plan','join_button','backgroundColor');set('.login-link,.profile-login-button','login_button');set('.feed-filter','feed_filter');set('.page-header h2,.feed-top h1,.profile-intro h2','page_heading');set('.post-body,.page-view,.sidebar-bottom p','body_text');set('.post,.profile-empty,.discover-result,.activity-list,.message-list,.settings-list','card_background','backgroundColor');set('.like,.notification-mark,.profile-event>span','reaction');}
 applyAdminStyles();
 function refreshPageCopy(){if(pageView.hidden)return;const page=document.querySelector('[data-page].active')?.dataset.page;const copy={discover:[adminContent.discover_eyebrow||'Find your people',adminContent.discover_title||'Discover plans worth joining.'],notifications:[adminContent.notification_eyebrow||'Stay in the loop',adminContent.notification_title||'Notifications'],messages:[adminContent.messages_eyebrow||'Keep the plan moving',adminContent.messages_title||'Messages'],settings:[adminContent.settings_eyebrow||'Make it yours',adminContent.settings_title||'Settings']};const values=copy[page];if(!values)return;const heading=pageView.querySelector('.page-header h2');const eyebrow=pageView.querySelector('.page-header .overline');if(heading&&values[1])heading.textContent=values[1];if(eyebrow&&values[0])eyebrow.textContent=values[0]}
  document.querySelectorAll('[data-page]').forEach(link=>link.addEventListener('click',()=>setTimeout(()=>{applyAdminContent();applyAdminStyles();refreshPageCopy()},150)));
 function replaceBrand(){document.querySelectorAll('body *').forEach(element=>element.childNodes.forEach(node=>{if(node.nodeType===Node.TEXT_NODE&&node.nodeValue.includes('upneXt'))node.nodeValue=node.nodeValue.replaceAll('upneXt','Evenit')}))}
replaceBrand();
const brandObserver=new MutationObserver(replaceBrand);
brandObserver.observe(document.body,{childList:true,subtree:true});
})();
