const posts = [
  {user:'maya.rose', name:'Maya Rose', avatar:'https://i.pravatar.cc/100?img=25', time:'2h', image:'pic-one', title:'Sunset picnic', location:'Prospect Park · Today, 5:00 PM', caption:'The blanket is packed and the sky is looking promising. Bringing snacks, sketchbooks, and room for a few more. Who’s in? ✦', likes:128, comments:14, joined:false},
  {user:'ari.makes', name:'Ari M.', avatar:'https://i.pravatar.cc/100?img=47', time:'5h', image:'pic-two', title:'Sunday people', location:'Red Hook · Sun, 10:30 AM', caption:'A little walk, a really good coffee, and some new neighborhood friends. Low-pressure plans are the best plans.', likes:86, comments:9, joined:false}
];
const postsEl=document.querySelector('#posts');
const hasSupabase=window.SUPABASE_URL&&!window.SUPABASE_URL.startsWith('YOUR_')&&window.SUPABASE_ANON_KEY&&!window.SUPABASE_ANON_KEY.startsWith('YOUR_');
const supabase=hasSupabase?window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY):null;
let currentUser=null;
const mapUrl=place=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place)}`;
function renderPosts(){postsEl.innerHTML=posts.map((post,index)=>`<article class="post"><header class="post-head"><img src="${post.avatar}" alt="${post.name}"><div><strong>${post.user}</strong><small>${post.time} · <a class="place" href="${mapUrl(post.location)}" target="_blank" rel="noreferrer">${post.location} ↗</a></small></div><button class="more">•••</button></header><div class="post-visual ${post.image}"><div class="visual-label"><small>upneXt plan</small><h2>${post.title}</h2><p>${post.location}</p></div></div><div class="post-actions"><button class="action like ${post.liked?'liked':''}" data-index="${index}">${post.liked?'👍':'👍🏻'}</button><button class="action comment" data-index="${index}">◯</button><button class="action share" data-index="${index}">⌁</button><button class="action save ${post.saved?'saved':''}" data-index="${index}">${post.saved?'◆':'◇'}</button></div><div class="post-body"><p class="likes">${post.likes+(post.liked?1:0)} people are interested</p><p class="caption"><strong>${post.user}</strong>${post.caption} <a href="#">#${post.title.replaceAll(' ','')}</a></p><p class="comments">View all ${post.comments} comments</p><button class="join-plan ${post.joined?'joined':''}" data-index="${index}">${post.joined?'Joined ✓':'Join in'} <span>→</span></button></div></article>`).join('');
  document.querySelectorAll('.like').forEach(btn=>btn.onclick=()=>{const p=posts[btn.dataset.index];p.liked=!p.liked;renderPosts()});document.querySelectorAll('.save').forEach(btn=>btn.onclick=()=>{posts[btn.dataset.index].saved=!posts[btn.dataset.index].saved;showToast(posts[btn.dataset.index].saved?'Saved to your plans':'Removed from saved plans');renderPosts()});document.querySelectorAll('.share').forEach(btn=>btn.onclick=()=>showToast('Plan link copied to clipboard ✦'));document.querySelectorAll('.comment').forEach(btn=>btn.onclick=()=>showToast('Comments are coming next ✦'));document.querySelectorAll('.join-plan').forEach(btn=>btn.onclick=()=>{const post=posts[btn.dataset.index];post.joined=!post.joined;showToast(post.joined?'You’re joining this plan! ✦':'You left this plan');renderPosts()});
}
renderPosts();
const pageView=document.querySelector('#page-view');
const homeElements=[document.querySelector('.feed-top'),document.querySelector('.stories'),postsEl];
const pageTemplates={
  discover:`<div class="page-header"><p class="overline">Find your people</p><h2>Discover plans<br><em>worth joining.</em></h2><div class="search-box">⌕ <input placeholder="Search plans, places, or people..."></div></div><div class="discover-grid"><div class="discover-tile tile-violet"><small>OUTDOORS</small><strong>Golden hour<br>on the water</strong><span>16 people going →</span></div><div class="discover-tile tile-gold"><small>FOOD & DRINK</small><strong>Sunday supper<br>club</strong><span>12 people going →</span></div><div class="discover-tile tile-ink"><small>CREATIVE</small><strong>Make a tiny<br>zine together</strong><span>8 people going →</span></div></div>`,
  notifications:`<div class="page-header"><p class="overline">Stay in the loop</p><h2>Notifications</h2></div><div class="activity-list"><div class="activity"><img src="https://i.pravatar.cc/100?img=47"><p><strong>ari.makes</strong> joined your plan <b>Sunset picnic</b><small>12 minutes ago</small></p></div><div class="activity"><img src="https://i.pravatar.cc/100?img=25"><p><strong>maya.rose</strong> liked your plan <b>Saturday sketch walk</b><small>1 hour ago</small></p></div><div class="activity"><img src="https://i.pravatar.cc/100?img=44"><p><strong>theo.walks</strong> started following you<small>Yesterday</small></p></div></div>`,
  messages:`<div class="page-header"><p class="overline">Keep the plan moving</p><h2>Messages</h2></div><div class="message-list"><div class="message"><img src="https://i.pravatar.cc/100?img=25"><div><strong>maya.rose</strong><p>Should we bring extra blankets for the picnic?</p></div><small>2m</small></div><div class="message"><img src="https://i.pravatar.cc/100?img=47"><div><strong>ari.makes</strong><p>That coffee walk sounds perfect.</p></div><small>1h</small></div><div class="empty-message">Your conversations will live here.<br><span>Join a plan to meet someone new.</span></div></div>`,
  settings:`<div class="page-header"><p class="overline">Make it yours</p><h2>Settings</h2></div><div class="settings-list"><button>Account details <span>→</span></button><button>Notification preferences <span>→</span></button><button>Privacy and safety <span>→</span></button><button>Help center <span>→</span></button></div>`,
};
function renderProfile(){const name=currentUser?.user_metadata?.full_name||currentUser?.email?.split('@')[0]||'Jamie Morgan';const username=currentUser?.user_metadata?.username||'jamie.morgan';pageView.innerHTML=`<div class="profile-cover"></div><div class="profile-intro"><img src="${currentUser?.user_metadata?.avatar_url||'https://i.pravatar.cc/160?img=68'}"><div><p class="overline">Your profile</p><h2>${name}</h2><p class="profile-handle">@${username}</p></div><button class="edit-profile">Edit profile</button></div><div class="profile-stats"><span><strong>0</strong> plans posted</span><span><strong>0</strong> joined</span><span><strong>0</strong> followers</span></div><div class="profile-tabs"><button class="active">Your plans</button><button>Joined</button><button>Saved</button></div><div class="profile-empty"><span>✦</span><h3>Your plans will appear here</h3><p>Share an idea and give people a reason to show up.</p><button class="publish-button" id="profile-post">Post a plan</button></div>`;document.querySelector('#profile-post').onclick=()=>modal.classList.add('open')}
function setPage(page){homeElements.forEach(element=>element.hidden=page!=='home');pageView.hidden=page==='home';document.querySelectorAll('[data-page]').forEach(link=>link.classList.toggle('active',link.dataset.page===page));if(page!=='home'){if(page==='profile')renderProfile();else pageView.innerHTML=pageTemplates[page]||pageTemplates.settings}window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-page]').forEach(link=>link.onclick=e=>{e.preventDefault();setPage(link.dataset.page)});
if(supabase){supabase.auth.getSession().then(({data})=>{currentUser=data.session?.user||null});supabase.auth.onAuthStateChange((_event,session)=>{currentUser=session?.user||null})}
const modal=document.querySelector('#modal');document.querySelector('#open-modal').onclick=()=>modal.classList.add('open');document.querySelector('#close-modal').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
const loginModal=document.querySelector('#login-modal');document.querySelector('#open-login').onclick=()=>loginModal.classList.add('open');document.querySelector('#close-login').onclick=()=>loginModal.classList.remove('open');loginModal.onclick=e=>{if(e.target===loginModal)loginModal.classList.remove('open')};document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();const data=new FormData(e.target);if(!supabase){showToast('Add your Supabase keys to connect login ✦');return}const {error}=await supabase.auth.signInWithPassword({email:data.get('email'),password:data.get('password')});if(error){showToast(error.message);return}loginModal.classList.remove('open');showToast('Welcome back to upneXt ✦')};document.querySelector('#signup-link').onclick=e=>{e.preventDefault();loginModal.classList.remove('open');showToast('Profile creation is coming next ✦')};
const signupModal=document.querySelector('#signup-modal');document.querySelector('#close-signup').onclick=()=>signupModal.classList.remove('open');signupModal.onclick=e=>{if(e.target===signupModal)signupModal.classList.remove('open')};document.querySelector('#signup-link').onclick=e=>{e.preventDefault();loginModal.classList.remove('open');signupModal.classList.add('open')};document.querySelector('#back-to-login').onclick=e=>{e.preventDefault();signupModal.classList.remove('open');loginModal.classList.add('open')};document.querySelector('#signup-form').onsubmit=async e=>{e.preventDefault();const data=new FormData(e.target);if(!supabase){showToast('Add your Supabase keys to connect signup ✦');return}const {data:result,error}=await supabase.auth.signUp({email:data.get('email'),password:data.get('password'),options:{data:{username:data.get('username'),full_name:data.get('full_name')}}});if(error){showToast(error.message);return}currentUser=result.user;signupModal.classList.remove('open');showToast('Profile created. Check your email to confirm ✦');setPage('profile')};
document.querySelector('#post-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);posts.unshift({user:'jamie.morgan',name:'Jamie Morgan',avatar:'https://i.pravatar.cc/100?img=68',time:'now',image:'pic-one',title:data.get('title'),location:data.get('where')+' · '+data.get('when'),caption:data.get('caption')||'A new plan is taking shape. Come as you are and make it yours. ✦',likes:0,comments:0,liked:false,saved:false});renderPosts();modal.classList.remove('open');e.target.reset();showToast('Your plan is live on upneXt ✦')};
function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
